export const bingoData = {
  title: "GTGC Bingo",
  freeSpaceText: "This is an analysis show, not a review show...",
  entries: [
    "Mention of Dustin being a PHD",
    "Arthurtron 5000",
    "No hosts have seen film before.",
    "All hosts have seen film before.",
    "Talk about getting old",
    "Death of movies",
    "Marx",
    "Foucault",
    "David Lynch",
    "All hosts would shelf",
    "All hosts would trash",
    "Dustin mentions a film no other hosts have seen",
    "Film everyone but Dustin has seen",
    "Guest Host",
    "Moving into reviews before giving the recap",
    "Arthur wants to 'gently place on pile'",
    "Dalton calls for something to burn or die in a fire",
    "There is mail",
    "Audio issues",
    "Someone mentions the behind the scenes of the show",
    "OFX",
    "American empire",
    "Capitalism",
    "AI being evil",
    "Reference to The Praisedown",
    "Oklahoma-centric historical atrocity",
    "Local band mentioned",
    "River mentioned",
    "Caleb Masters mentioned",
    "Reference to someone moving to LA"
  ]
};
